export class ClienteIndex {
   
    //CLIENTE
        IDCLIENTE:number
        CLIENTE:string
        RUC:string
        CONTRIBUYENTE:string
        TIPO_CONTRIBUYENTE:string
        CATEGORIA_CLIENTE:string
        NOMBRE:string
        PAIS:string
        DIRECCION:string
        EMAIL:string
        TELEFONO1:string
        TELEFONO2:string
        MOROSO:string
        USUARIO_CREACION:string
        USUARIO_ULT_MOD:string
        ACTIVO:string
        
    constructor(
            IDCLIENTE:number,
            CLIENTE:string,
            RUC:string,
            CONTRIBUYENTE:string,
            TIPO_CONTRIBUYENTE:string,
            CATEGORIA_CLIENTE:string,
            NOMBRE:string,
            PAIS:string,
            DIRECCION:string,
            EMAIL:string,
            TELEFONO1:string,
            TELEFONO2:string,
            MOROSO:string,
            USUARIO_CREACION:string,
            USUARIO_ULT_MOD:string,
            ACTIVO:string
        )
        {
            this.IDCLIENTE=IDCLIENTE;
            this.CLIENTE=CLIENTE;
            this.RUC=RUC;
            this.CONTRIBUYENTE=CONTRIBUYENTE;
            this.TIPO_CONTRIBUYENTE=TIPO_CONTRIBUYENTE;
            this.CATEGORIA_CLIENTE=CATEGORIA_CLIENTE;
            this.NOMBRE=NOMBRE;
            this.PAIS=PAIS;
            this.DIRECCION=DIRECCION;
            this.EMAIL=EMAIL;
            this.TELEFONO1=TELEFONO1;
            this.TELEFONO2=TELEFONO2;
            this.MOROSO=MOROSO;
            this.USUARIO_CREACION=USUARIO_CREACION;
            this.USUARIO_ULT_MOD=USUARIO_ULT_MOD;
            this.ACTIVO=ACTIVO;
        }

    }
